exports.brandList = [
  'Monogram',
  'Abracadabra',
  'SEY',
  'George Howell',
  'Brandywine',
  'Proud Mary',
  'Valor',
  'Square Mile',
  'Middle State',
  'Intelligentsia',
  'Verve',
  'Traffic',
  'Phil & Sebastian',
  'Santi Henri',
  'Little Sister',
  'Process',
  'Stumptown',
  'La Cabra',
  'Thom Bargen',
  'Camber',
  'Sweet Bloom',
  'Fritz',
  'Luna',
  'Barn',
  'Karasu',
  'House of Funk',
  'Kudu',
  'Onyx',
  'Rogue Wave',
  'Dak',
  'Kurasu',
  '3fe',
  'Night Swim',
  'Gardelli'
]